### ISSUE TITLE
Extension does not consider rules in stylecop.json

### ISSUE THREAD

**Issue by epitka** [StyleCop/StyleCop.ReSharper#16]
I have following stylecop.json file where it is declared that using directives should be outside of namespace. However every time I let R# import directives it places them within namespace. How can this be fixed?

{
  "$schema":
    "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "orderingRules": {
      "usingDirectivesPlacement": "outsideNamespace"
    },
    "documentationRules": {
      "xmlHeader": false,
      "documentInterfaces": false,
      "documentInternalElements": false,
      "documentExposedElements": false,
      "excludeFromPunctuationCheck": [
        "seealso",
        "param",
        "returns",
        "summary"
      ]
    }
  }
}

**Comment by ianelletson** [comment]
Same issue. Extension seems valuable but is effectively unusable without it.

**Comment by softworkz** [comment]
Same for me..

**Comment by matkoch** [comment]
This extension only takes the `StyleCop.Settings` file into account. As of now, there is no mapping between the `StyleCop.json` and ReSharper settings.

**Comment by matkoch** [comment]
https://youtrack.jetbrains.com/issue/RIDER-26163

**Comment by softworkz** [comment]
Did I get this right that those files share the same internal structure, so it would be sufficient to duplicate StyleCop.json as StyleCop.Settings?

**Comment by matkoch** [comment]
I think it would rather make sense to directly set the ReSharper settings.

**Comment by softworkz** [comment]
Hm, but ReSharper is applying the StyleCop fixes like it is supposed to do and that includes the header writing, so the ReSharper header template doesn't get used here.

Or can this behaviour be changed?

BTW, another annoyance is this:

![image](https://user-images.githubusercontent.com/4985349/55692056-991f8880-59a4-11e9-9189-241385c80771.png)

The number of dashes in file header text cannot be set to 0. That's really unfortunate because it's impossible to have the headers filled without the two lines containing dashes..
