### ISSUE TITLE
Code clean up adds explicit lambda expression parameter types

### ISSUE THREAD

**Issue by j-bernhard** [StyleCop/StyleCop.ReSharper#59]
I talked with the Resharper support and they said I should opene an issue on the StyleCope.Resharper extension. 

The problem is that if I have installed the StyleCop.Resharper extension every time I do a code cleanup explicit types are added for lambda expression. But on the other hand stylecop says, redundant explicit type parameter on lambda. (I like the implicit using as it was before. Actual I found no option to configure the old behavior.) 

![image](https://github.com/StyleCop/StyleCop.ReSharper/assets/8314146/476bf576-9b3a-4361-89ea-ac8c3cd411f5)

![image](https://github.com/StyleCop/StyleCop.ReSharper/assets/8314146/664845b9-17f7-4a68-b1fb-56bae01cb24a)

Example Project and Video
[Aufzeichnung 2023-10-26 082844.zip](https://github.com/StyleCop/StyleCop.ReSharper/files/13220237/Aufzeichnung.2023-10-26.082844.zip)

**Comment by 5p1k3md** [comment]
I would like to hear a solution for this as well, because it is quite annoying.

**Comment by SteveKalk** [comment]
I have the same problem and am also waiting for a solution!

**Comment by matkoch** [comment]
Please see the note in the readme:

![2023-12-10-Arc-StyleCopStyleCop ReSharper Official ReSharper extension for StyleCop-001475](https://github.com/StyleCop/StyleCop.ReSharper/assets/5005566/f1f889f6-c9c0-40e3-bb07-e0693d310c37)

I will consider a new approach since this text seems to go unnoticed by many users.
