### ISSUE TITLE
Can we have this plugin available for ReSharper Ultimate 2018.2 EAP?

### ISSUE THREAD

**Issue by NikolayIT** [StyleCop/StyleCop.ReSharper#8]
The only thing that stops me from using EAP versions is the lack of StyleCop for ReSharper plugin.

**Comment by matkoch** [comment]
I've uploaded a new package for [2018.2.0-eap1](https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2018.2.0-eap1).

Could you ping me whenever the plugin is not working correctly during EAP? I will make a new prerelease then. The process of upgrading is very cumbersome due to the old project format (SDK-based is currently not working) and the amount of testing it would involve.

**Comment by NikolayIT** [comment]
Hello @matkoch,
I don't see the plugin in the extensions list.
Actually I don't see any extensions there:
![image](https://user-images.githubusercontent.com/3106986/42413100-faed22bc-8221-11e8-818f-b1ecfd4e9533.png)

**Comment by matkoch** [comment]
@NikolayIT do you have `https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v182.0/` enabled as a source?

**Comment by NikolayIT** [comment]
@matkoch Thank you. Installed it already. It works fine.

**Comment by NikolayIT** [comment]
I added it manually.

**Comment by matkoch** [comment]
@NikolayIT what you were facing is an issue tracked here: https://youtrack.jetbrains.com/issue/RSRP-470442
